// Built-in fallback data when GitHub is unreachable
const fallbackProjects = [
  {
    rank: 1,
    owner: "microsoft",
    name: "TypeScript",
    fullName: "microsoft/TypeScript",
    url: "https://github.com/microsoft/TypeScript",
    description: "TypeScript is a superset of JavaScript that compiles to clean JavaScript output.",
    language: "TypeScript",
    totalStars: 102000,
    forks: 13500,
    starsThisPeriod: 2847,
    contributors: ["DanielRosenwasser", "RyanCavanaugh", "sheetalkamat", "weswigham", "jakebailey"],
  },
  {
    rank: 2,
    owner: "facebook",
    name: "react",
    fullName: "facebook/react",
    url: "https://github.com/facebook/react",
    description: "The library for web and native user interfaces.",
    language: "JavaScript",
    totalStars: 231000,
    forks: 47300,
    starsThisPeriod: 2156,
    contributors: ["gaearon", "acdlite", "sebmarkbage", "sophiebits", "rickhanlonii"],
  },
  {
    rank: 3,
    owner: "langchain-ai",
    name: "langchain",
    fullName: "langchain-ai/langchain",
    url: "https://github.com/langchain-ai/langchain",
    description: "🦜🔗 Build context-aware reasoning applications",
    language: "Python",
    totalStars: 98500,
    forks: 15800,
    starsThisPeriod: 1980,
    contributors: ["hwchase17", "agola11", "baskaryan", "eyurtsev", "jacoblee93"],
  },
  {
    rank: 4,
    owner: "vercel",
    name: "next.js",
    fullName: "vercel/next.js",
    url: "https://github.com/vercel/next.js",
    description: "The React Framework for the Web",
    language: "JavaScript",
    totalStars: 129000,
    forks: 27700,
    starsThisPeriod: 1750,
    contributors: ["timneutkens", "ijjk", "shuding", "huozhi", "ztanner"],
  },
  {
    rank: 5,
    owner: "oven-sh",
    name: "bun",
    fullName: "oven-sh/bun",
    url: "https://github.com/oven-sh/bun",
    description: "Incredibly fast JavaScript runtime, bundler, test runner, and package manager.",
    language: "Zig",
    totalStars: 76500,
    forks: 2800,
    starsThisPeriod: 1620,
    contributors: ["Jarred-Sumner", "paperdave", "dylan-conway", "Hanaasagi", "Electroid"],
  },
  {
    rank: 6,
    owner: "supabase",
    name: "supabase",
    fullName: "supabase/supabase",
    url: "https://github.com/supabase/supabase",
    description: "The open source Firebase alternative.",
    language: "TypeScript",
    totalStars: 74200,
    forks: 7400,
    starsThisPeriod: 1480,
    contributors: ["kiwicopple", "MildTomato", "soedirgo", "inian", "dragarcia"],
  },
  {
    rank: 7,
    owner: "rustdesk",
    name: "rustdesk",
    fullName: "rustdesk/rustdesk",
    url: "https://github.com/rustdesk/rustdesk",
    description: "An open-source remote desktop application designed for self-hosting.",
    language: "Rust",
    totalStars: 78000,
    forks: 10900,
    starsThisPeriod: 1350,
    contributors: ["rustdesk", "21pages", "fufesou", "Heap-Hop", "Kingtous"],
  },
  {
    rank: 8,
    owner: "ollama",
    name: "ollama",
    fullName: "ollama/ollama",
    url: "https://github.com/ollama/ollama",
    description: "Get up and running with Llama 3.3, DeepSeek-R1, Phi-4, Gemma 3, Mistral and other large language models.",
    language: "Go",
    totalStars: 112000,
    forks: 9100,
    starsThisPeriod: 3200,
    contributors: ["mchiang0610", "BruceMacD", "jmorganca", "pdevine", "dhiltgen"],
  },
  {
    rank: 9,
    owner: "tauri-apps",
    name: "tauri",
    fullName: "tauri-apps/tauri",
    url: "https://github.com/tauri-apps/tauri",
    description: "Build smaller, faster, and more secure desktop and mobile applications with a web frontend.",
    language: "Rust",
    totalStars: 86200,
    forks: 2650,
    starsThisPeriod: 1180,
    contributors: ["lucasfernog", "amrbashir", "FabianLars", "chippers255", "tweidinger"],
  },
  {
    rank: 10,
    owner: "shadcn-ui",
    name: "ui",
    fullName: "shadcn-ui/ui",
    url: "https://github.com/shadcn-ui/ui",
    description: "Beautifully designed components that you can copy and paste into your apps.",
    language: "TypeScript",
    totalStars: 75000,
    forks: 4650,
    starsThisPeriod: 1950,
    contributors: ["shadcn", "dan5py", "joe-bell", "n1ru4l", "martygo"],
  },
  {
    rank: 11,
    owner: "excalidraw",
    name: "excalidraw",
    fullName: "excalidraw/excalidraw",
    url: "https://github.com/excalidraw/excalidraw",
    description: "Virtual whiteboard for sketching hand-drawn like diagrams",
    language: "TypeScript",
    totalStars: 86500,
    forks: 8800,
    starsThisPeriod: 1050,
    contributors: ["dwelle", "lipis", "ad1992", "vjeux", "benoit-deschasaux"],
  },
  {
    rank: 12,
    owner: "appwrite",
    name: "appwrite",
    fullName: "appwrite/appwrite",
    url: "https://github.com/appwrite/appwrite",
    description: "Build like a team of hundreds_",
    language: "TypeScript",
    totalStars: 45800,
    forks: 6200,
    starsThisPeriod: 920,
    contributors: ["eldadfux", "christyjacob4", "TorstenDittmann", "loks0n", "stnguyen90"],
  },
  {
    rank: 13,
    owner: "payloadcms",
    name: "payload",
    fullName: "payloadcms/payload",
    url: "https://github.com/payloadcms/payload",
    description: "Payload is the open-source, fullstack Next.js framework.",
    language: "TypeScript",
    totalStars: 29800,
    forks: 1800,
    starsThisPeriod: 880,
    contributors: ["jmikrut", "DanRibbens", "denolfe", "AlessioGr", "jacobsfletch"],
  },
  {
    rank: 14,
    owner: "microsoft",
    name: "vscode",
    fullName: "microsoft/vscode",
    url: "https://github.com/microsoft/vscode",
    description: "Visual Studio Code",
    language: "TypeScript",
    totalStars: 166000,
    forks: 30100,
    starsThisPeriod: 1560,
    contributors: ["bpasero", "jrieken", "alexdima", "Tyriar", "hediet"],
  },
  {
    rank: 15,
    owner: "toeverything",
    name: "AFFiNE",
    fullName: "toeverything/AFFiNE",
    url: "https://github.com/toeverything/AFFiNE",
    description: "There can be more than Notion and Miro. AFFiNE is a next-gen knowledge base.",
    language: "TypeScript",
    totalStars: 42500,
    forks: 2800,
    starsThisPeriod: 820,
    contributors: ["himself65", "darkskygit", "pengx17", "EYHN", "lawvs"],
  },
  {
    rank: 16,
    owner: "curl",
    name: "curl",
    fullName: "curl/curl",
    url: "https://github.com/curl/curl",
    description: "A command line tool and library for transferring data with URL syntax.",
    language: "C",
    totalStars: 36500,
    forks: 6650,
    starsThisPeriod: 450,
    contributors: ["bagder", "jay", "dfandrich", "icing", "monnerat"],
  },
  {
    rank: 17,
    owner: "sveltejs",
    name: "svelte",
    fullName: "sveltejs/svelte",
    url: "https://github.com/sveltejs/svelte",
    description: "Cybernetically enhanced web apps",
    language: "JavaScript",
    totalStars: 79800,
    forks: 4300,
    starsThisPeriod: 780,
    contributors: ["Rich-Harris", "dummdidumm", "Conduitry", "trueadm", "benmccann"],
  },
];

module.exports = { fallbackProjects };
